#!/usr/bin/perl

=head1 NAME

check-io-util - Plugin to check %util of iostat.

=head1 SYNOPSIS

    check-io-util [ OPTIONS ]

    check-io-util --help

=head1 REPORTING BUGS

Please report all bugs to <hallo(at)dominicpratt.de>.

=head1 AUTHOR

Dominic Pratt <hallo(at)dominicpratt.de>.

=cut

use strict;
use warnings;
use Bloonix::Plugin;

my $plugin = Bloonix::Plugin->new(version => "0.1");

$plugin->example(
    description => "Parse the output of %util in iostat -x.",
    arguments => [ disk => "sda" ]
);

$plugin->add_option(
    name => "Device name",
    option => "device",
    value => "device",
    multiple => 0,
    mandatory => 1,
    regex => qr/^[a-zA-Z_0-9]+\z/,
    value_type => "string",
    description => "This is the device name to check."
);

my $opt = $plugin->parse_options;

my $iostat = qx{which iostat};
chomp $iostat;

if (!$iostat || !-x $iostat) {
    $plugin->exit(
        status => "UNKNOWN",
        message => "command 'iostat' not found"
    );
}

my @output = qx{$iostat -d -x '$opt->{device}'};
my $util;

foreach my $line (@output) {
    if ($line =~ /^$opt->{device}/) {
        $util = (split /\s+/, $line)[13];
    }
}

if (!defined $util || !length $util) {
    $plugin->exit(
        status => "UNKNOWN",
        message => "device $opt->{device}' not found"
    );
}

$plugin->exit(
    status => "OK",
    message => "%util: $util",
    stats => {
        util => $util
    }
);

