#!/usr/bin/perl

=head1 NAME

check-io-util - Plugin to check %util of iostat.

=head1 SYNOPSIS

    check-io-util [ OPTIONS ]

    check-io-util --help

=head1 REPORTING BUGS

Please report all bugs to <hallo(at)dominicpratt.de>.

=head1 AUTHOR

Dominic Pratt <hallo(at)dominicpratt.de>.

=cut

use strict;
use warnings;
use Bloonix::Plugin;

my $plugin = Bloonix::Plugin->new(version => "0.1");

$plugin->example(
    description => "Parse the output of %util in iostat -x.",
    arguments => [ disk => "sda" ]
);

$plugin->add_option(
    name => "Device name",
    option => "device",
    value => "device",
    multiple => 0,
    mandatory => 1,
    regex => qr/^[a-zA-Z_0-9]+\z/,
    value_type => "string",
    description => "This is the device name to check."
);

$plugin->has_timeout(default => 10);

my $opt = $plugin->parse_options;

my $util = `/usr/bin/iostat -d -x '$opt->{device}' | /usr/bin/awk '/^'$opt->{device}/' {print \$14}'`;
chomp $util;

my $status = "OK";

$plugin->exit(
    status => $status,
    message => "%util: $util",
    stats => $util
);

